[workspace]
members = [
]
[package]
name = "buffer-rs"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2018"
autobins = false

[[bin]]
name = "test"
path = "lib.rs"

[dependencies]
libc= "0.2"
